name: Deploy production

on: [workflow_dispatch]

env:
  REGISTRY_FROM: regdev13114.azurecr.io
  REGISTRY_TO: regprod13114.azurecr.io
  IMAGE: 'nico13114'

jobs:
  deploy-production:
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/heads/release/}
      - name: Build base image
        run: |
          echo $VERSION
          echo "github.run_id = ": ${{ github.run_id }}
        env:
          VERSION: ${{ steps.branch_name.outputs.VERSION }}

