name: Deploy in DEV

on:
  #The restriction to directly push commits to master solves the problem.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY_BASE: base13114.azurecr.io
  REGISTRY_APP: regdev13114.azurecr.io
  IMAGE: 'nico13114'
  APP_NAME: 'webdev13114'

jobs:
  #=====================================================================================================================
  # DEPLOY INTO DEV AUTOMATICALLY
  #=====================================================================================================================
  deploy-dev:
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: 'azure docker registry login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_BASE }}
          username: ${{ secrets.ACR_SECRET_ID }}
          password: ${{ secrets.ACR_SECRET_PWD }}
      - name: 'Build the image'
        id: build
        run: |
          docker build -t ${{ env.REGISTRY_APP }}/${{ env.IMAGE }}:uat .
      - name: 'azure registry login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_APP }}
          username: ${{ secrets.ACR_APP_SECRET_ID}}
          password: ${{ secrets.ACR_APP_SECRET_PWD }}
      - name: container structure test
        run: "echo container structure test"
      - name: push
        run: |
          docker push ${{ env.REGISTRY_APP }}/${{ env.IMAGE }}:uat
          docker tag ${{env.REGISTRY_APP}}/${{env.IMAGE}}:uat ${{ env.REGISTRY_APP }}/${{ env.IMAGE }}:${{ github.sha }}
          docker push ${{ env.REGISTRY_APP }}/${{ env.IMAGE }}:${{ github.sha }}
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          #publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          images: ${{env.REGISTRY_APP}}/${{ env.IMAGE }}:${{ github.sha }}
      - name: e2e
        run: "echo e2e"
      - name: perf
        run: "echo perf."
