name: Deploy WebApp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: baseartifacts.azurecr.io
  IMAGE: 'demo13114'

jobs:
  #=====================================================================================================================
  # DEPLOY INTO DEV AUTOMATICALLY
  #=====================================================================================================================
  deploy-dev:
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: 'azure registry login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_SECRET_ID }}
          password: ${{ secrets.ACR_SECRET_PWD }}
      - run: ls -la .
      - run: pwd
      - name: 'Build the image'
        id: build
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE }}:uat .
      - name: 'azure registry login'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ env.REGISTRY }}
            username: 1248cda0-dca5-4188-804d-7b268be7e79e
            password: O0_9IyoHZYHy5CWo53.U5D38VAYQKqNZg_
          run: |
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:uat
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: uat-demo13114
          images: ${{env.REGISTRY}}/${{ env.IMAGE }}:uat
