name: Deploy WebApp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: baseartifacts.azurecr.io
  IMAGE: 'demo13114'

jobs:
  #=====================================================================================================================
  # DEPLOY INTO DEV AUTOMATICALLY
  #=====================================================================================================================
  deploy-dev:
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: ls -la .
      - run: pwd
      - name: 'Build the image'
        id: build
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE }}:uat .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:uat

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: uat-demo13114
          images: ${{env.REGISTRY}}/${{ env.IMAGE }}:uat
